### ISSUE TITLE
What are the guarantees when iterating with Front() and Next()?

### ISSUE THREAD

**Issue by 0joshuaolson1** [sean-public/fast-skiplist#6]
Can concurrent modifications ever cause a problem?

**Comment by sean-public** [comment]
Yes, it would be up to the application using this library to decide to lock the whole data structure around a series of reads if they wanted to ensure no writes occurred. For example, if you wanted to read the value at a given node plus the 10 nodes following it, you would want to lock during that read if your concurrent access model could also permit insert/delete/update of those same nodes.

Perhaps a good solution would be to add a `Range()` to the data structure that acquired a lock for the duration? My initial decision was to leave that up to the caller because I didn't think the lib should allocate and return sub-lists.
